import { expect, test } from "@playwright/test";
import { credentials, signIn } from "./local-fixtures";

const alpha = "http://alpha.courses.test";

test("shared theme, table state, drawer focus and responsive overflow work together", async ({ page }) => {
  const owner = credentials("alpha");
  await signIn(page, alpha, owner.email, owner.password);
  await expect(page.getByRole("table", { name: "الفروع", exact: true })).toBeVisible();
  let clientApiRequests = 0;
  page.on("request", (request) => { if (request.url().includes("/api/v1/center/")) clientApiRequests++; });
  await page.getByRole("button", { name: "تفعيل الوضع الداكن" }).click();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.getByRole("button", { name: "طي القائمة الجانبية" }).click();
  await expect(page.getByRole("link", { name: "إدارة الموظفين والدعوات" })).toBeVisible();
  await page.getByRole("searchbox", { name: "بحث في الفروع" }).fill("no-matching-branch-qa");
  await expect(page.getByRole("heading", { name: "لا توجد نتائج مطابقة" })).toBeVisible();
  await page.getByRole("button", { name: "مسح البحث في الفروع", exact: true }).click();
  await expect(page.getByRole("searchbox", { name: "بحث في الفروع" })).toBeFocused();
  await expect(page.locator(".data-panel")).toHaveAttribute("data-density", "compact");
  await expect(page.getByRole("button", { name: "مكثّف", exact: true })).toHaveCount(0);
  expect(clientApiRequests).toBe(0);
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.goto(`${alpha}/admin?branches-density=compact&branches-page=999`);
  await expect(page.getByRole("table", { name: "الفروع", exact: true })).toBeVisible();
  await expect(page).not.toHaveURL(/branches-page=/);
  await expect(page.getByRole("button", { name: "الصفحة التالية في الفروع" })).toBeDisabled();
  await page.getByRole("searchbox", { name: "بحث في الفروع" }).fill("الشمالي");
  await page.reload();
  await expect(page.getByRole("searchbox", { name: "بحث في الفروع" })).toHaveValue("الشمالي");
  await expect(page.getByRole("heading", { name: "الفرع الجنوبي" })).toHaveCount(0);
  await page.getByRole("button", { name: "مسح البحث في الفروع", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "القائمة", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("button", { name: "إغلاق القائمة" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "القائمة", exact: true })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  expect(await page.locator(".table-scroll").evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(true);
  await page.getByRole("button", { name: "إنشاء فرع", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "اسم الفرع", exact: true })).toBeFocused();
  await page.getByRole("form", { name: "فرع جديد" }).getByRole("button", { name: "إلغاء", exact: true }).click();
  await expect(page.getByRole("button", { name: "إنشاء فرع", exact: true })).toBeFocused();
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole("link", { name: "إدارة الموظفين والدعوات", exact: true }).click();
  await expect(page.getByRole("table", { name: "الدعوات", exact: true })).toBeVisible();
  await expect(page.getByRole("table", { name: "العضويات", exact: true })).toBeVisible();
  await expect(page.locator(".center-topbar").getByRole("heading", { name: "موظفو المركز", exact: true })).toBeVisible();
  await expect(page.locator(".center-topbar").getByRole("button", { name: "إرسال الدعوة", exact: true })).toHaveAttribute("form", "invite-member");
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  expect(await page.locator(".center-topbar").evaluate((element) => Math.round(element.getBoundingClientRect().top))).toBe(0);
  expect(await page.locator(".sidebar-bottom").evaluate((element) => element.getBoundingClientRect().bottom <= window.innerHeight)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  const staff = page.getByRole("row").filter({ has: page.getByRole("heading", { name: "Staff Demo", exact: true }) });
  await staff.getByRole("button", { name: "إيقاف العضوية", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("button", { name: "إلغاء" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(staff.getByRole("button", { name: "إيقاف العضوية", exact: true })).toBeFocused();
  await page.getByRole("link", { name: "أمان الحساب", exact: true }).click();
  await page.getByRole("textbox", { name: "كلمة المرور الحالية" }).fill("preview-only");
  await page.getByRole("button", { name: "إظهار كلمة المرور الحالية" }).click();
  await expect(page.getByRole("textbox", { name: "كلمة المرور الحالية" })).toHaveAttribute("type", "text");
  await page.getByRole("button", { name: "إخفاء كلمة المرور الحالية" }).click();
  await expect(page.getByRole("textbox", { name: "كلمة المرور الحالية" })).toHaveAttribute("type", "password");
  await page.getByRole("link", { name: "سجل التدقيق", exact: true }).click();
  await expect(page.getByRole("table", { name: "الأحداث", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "إعدادات المركز", exact: true }).click();
  await expect(page.getByRole("button", { name: "حفظ الإعدادات", exact: true })).toBeVisible();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
});
