import { expect, test } from "@playwright/test";
import { credentials, signIn } from "./local-fixtures";

const alpha = "http://alpha.courses.test";
test("compact shared tables support saved columns, ordering and draft filters", async ({ page, browser }) => {
  const owner = credentials("alpha");
  await signIn(page, alpha, owner.email, owner.password);
  let requests = 0;
  page.on("request", (request) => { if (request.url().includes("/api/v1/center/")) requests++; });
  const table = page.getByRole("table", { name: "الفروع", exact: true });
  const keys = () => table.locator("thead th").evaluateAll((cells) => cells.map((cell) => cell.getAttribute("data-column-key")));
  await expect(page.locator(".data-panel")).toHaveAttribute("data-density", "compact");
  await expect(page.getByRole("group", { name: "كثافة جدول الفروع" })).toHaveCount(0);
  await page.getByRole("button", { name: "الأعمدة — الفروع", exact: true }).click();
  const columns = page.getByRole("dialog", { name: "الأعمدة المعروضة — الفروع", exact: true });
  await expect(columns.getByRole("checkbox", { name: "الفرع (دائمًا)" })).toBeDisabled();
  await expect(columns.getByRole("checkbox", { name: "الإجراءات (دائمًا)" })).toBeDisabled();
  await columns.getByRole("checkbox", { name: "العنوان", exact: true }).uncheck();
  await columns.getByRole("button", { name: "نقل رمز الفرع قبل العمود السابق" }).click();
  expect(await keys()).toEqual(["slug", "name", "actions"]);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "الأعمدة — الفروع", exact: true })).toBeFocused();
  await page.reload();
  await expect(table.getByRole("columnheader", { name: "العنوان", exact: true })).toHaveCount(0);
  await expect.poll(keys).toEqual(["slug", "name", "actions"]);
  await table.getByRole("columnheader", { name: "رمز الفرع", exact: true }).dragTo(table.getByRole("columnheader", { name: "الفرع", exact: true }));
  await expect.poll(keys).toEqual(["name", "slug", "actions"]);
  await table.getByRole("columnheader", { name: "الفرع", exact: true }).press("Alt+ArrowLeft");
  await expect.poll(keys).toEqual(["slug", "name", "actions"]);
  await expect(table.getByRole("columnheader", { name: "الفرع", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "الفلاتر — الفروع", exact: true }).click();
  const filters = page.getByRole("dialog", { name: "تصفية الفروع", exact: true });
  await filters.getByRole("textbox", { name: "الفرع", exact: true }).fill("الشمالي");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("heading", { name: "الفرع الجنوبي", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "الفلاتر — الفروع", exact: true }).click();
  await expect(filters.getByRole("textbox", { name: "الفرع", exact: true })).toHaveValue("");
  await filters.getByRole("textbox", { name: "العنوان", exact: true }).fill("القاهرة");
  await filters.getByRole("button", { name: "تطبيق", exact: true }).click();
  await expect(page.getByRole("heading", { name: "الفرع الجنوبي", exact: true })).toHaveCount(0);
  await expect(page).toHaveURL(/branches-f-address=/);
  await expect(page.getByRole("button", { name: "الفلاتر — الفروع", exact: true })).toContainText("١");
  expect(requests).toBe(0);
  await page.reload();
  await expect(page.getByRole("heading", { name: "الفرع الجنوبي", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "الفلاتر — الفروع", exact: true }).click();
  await filters.getByRole("button", { name: "مسح الفلاتر", exact: true }).click();
  await expect(page.getByRole("heading", { name: "الفرع الجنوبي", exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 600 });
  await page.getByRole("button", { name: "الأعمدة — الفروع", exact: true }).click();
  const bounds = await columns.boundingBox();
  expect(bounds).toBeTruthy();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(600);
  await columns.getByRole("button", { name: "استعادة الأعمدة الافتراضية" }).click();
  await expect.poll(keys).toEqual(["name", "slug", "address", "actions"]);
  await columns.getByRole("checkbox", { name: "العنوان", exact: true }).uncheck();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole("link", { name: "إدارة الموظفين والدعوات", exact: true }).click();
  await expect(page.getByRole("button", { name: "الأعمدة — العضويات", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "الفلاتر — الدعوات", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "الفلاتر — العضويات", exact: true }).click();
  const memberFilters = page.getByRole("dialog", { name: "تصفية العضويات", exact: true });
  await memberFilters.getByRole("radio", { name: "موقوف", exact: true }).check();
  await memberFilters.getByRole("button", { name: "تطبيق", exact: true }).click();
  await expect(page).toHaveURL(/members-filter=suspended/);
  const cookies = (await page.context().cookies()).filter((cookie) => cookie.name.startsWith("courses_table_"));
  const staffContext = await browser.newContext();
  try {
    await staffContext.addCookies(cookies);
    const staffPage = await staffContext.newPage();
    const staff = credentials("staff");
    await signIn(staffPage, alpha, staff.email, staff.password);
    await expect(staffPage.getByRole("table", { name: "الفروع", exact: true }).getByRole("columnheader", { name: "العنوان", exact: true })).toBeVisible();
  } finally { await staffContext.close(); }
});
